[package]
name = "guac-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql_client = {version = "0.12.0", features = ["reqwest-blocking"]}
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.56"
reqwest = { version = "^0.11", features = ["json", "blocking"] }
anyhow = "1.0.39"
log = "^0.4"
env_logger = "^0.5"

openvex = "0.1.0"
uuid = { version = "1.3.0", features = ["v4"] }
chrono = { version = "0.4.23", features = ["serde"] }
seedwing-policy-engine = "0.1.0-alpha.2"
packageurl = "0.3.0"